config/routes.rb
Rails.application.routes.draw do

  root to: 'static#homepage'

  resources :products
  resources :sub_sub_categories
  resources :sub_categories
  resources :categories
end

app/models/sub_sub_category.rb
class SubSubCategory < ActiveRecord::Base
  belongs_to :sub_category
  has_many :products, dependent: :destroy

  accepts_nested_attributes_for :products,
                       reject_if: proc { |attributes| attributes['name'].blank? },
                   allow_destroy: true

  validates :name, presence: true
  validates :name, uniqueness: true

  def sub_cat_data
    return { name: sub_category.name,
               id: sub_category.id }
  end
  def cat_data
    return { name: sub_category.category.name,
               id: sub_category.category.id }
  end
end

app/controllers/sub_sub_categories_controller.rb
class SubSubCategoriesController < ApplicationController
  before_action :set_sub_sub_category, only: [:show, :edit, :update, :destroy]

  def index
    @sub_sub_categories = SubSubCategory.all
  end

  def new
    @sub_sub_category = SubSubCategory.new
  end

  def create
    # debugger
    @sub_sub_category = SubSubCategory.new(sub_sub_category_params)

    if @sub_sub_category.save
      redirect_to sub_sub_categories_path, notice: 'Sub Sub Category was successfully created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @sub_sub_category.update(sub_sub_category_params)
      redirect_to @sub_sub_category, notice: 'Sub Sub Category was successfully updated!'
    else
      render :edit
    end
  end

  def show
    @sub_sub_category = SubSubCategory.order("updated_at DESC").limit(5)
  end

  def destroy
    @sub_sub_category.destroy
    redirect_to sub_sub_categories_path, notice: 'Sub Sub Category was successfully deleted'
  end

  private

  def sub_sub_category_params
    params.require(:sub_sub_category).permit(:name, :sub_category_id, products_attributes: [ :id, :name ])
  end

  def set_sub_sub_category
    @sub_sub_category = SubSubCategory.find(params[:id])
  end
end

app/helpers/sub_sub_categories_helper.rb
module SubSubCategoriesHelper
end

app/views/sub_sub_categories/_form.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <%= form_for @sub_sub_category, class: "form-horizontal" do |f| %>

      <% if @sub_sub_category.errors.any? %>
          <% @sub_sub_category.errors.full_messages.each do |error| %>
          <%= js add_gritter(error, title: "Sephora App Notification", sticky: false) %>
        <% end %>
      <% end %>

      <div class="form-group">
        <%= f.label :sub_category, class: "col-sm-4 control-label" %>
        <%= f.grouped_collection_select(:sub_category_id, Category.all, :sub_categories, :name, :id, :name, { :multiple => false }, {class: "form-control"}) %>
      </div>

      <div class="form-group">
        <%= f.label :name, class: "col-sm-2 control-label" %>
        <%= f.text_area :name, class: "form-control" %>
      </div>

      <% unless create_page?(new_sub_category_path) %>
      <h3>Products</h3>
        <div class="container product-container">
          <div class="row product-container-row">
            <%= f.fields_for :products do |product| %>
              <%= render 'product_card', product: product %>
            <% end %>
          </div>
        </div></br>
      <% end %>

      <%= link_to 'Create new product', new_product_path, class: 'btn btn-xs btn-primary btn-block' %>
      <%= f.submit 'Save', class: 'btn btn-success btn-block' %>

    <% end %>
  </div>
</div>

app/views/sub_sub_categories/_product_card.html.erb
<div class="col-xs-3">
  <div class="project project-default">
    <div class="project-content">
      <h5 class="lead">
        <%= product.label :name, 'Name: ', class: 'product-card-text' %>
        <%= product.text_field :name, class: "form-control" %>
      </h5>
      <p>
        <%= product.label :description, class: 'product-card-text' %>
        <%= product.text_field :description, class: "form-control" %>
      </p>
      <p>
        <%= product.label :price, class: 'product-card-text' %>
        <%= product.number_field :price, class: "form-control" %>
      </p>
    </div>
  </div>
</div>

app/views/sub_sub_categories/_sub_sub_category.html.erb
<tr>
	<td>
		<%= sub_sub_category.id %>
	</td>
	<td>
		<%= link_to sub_sub_category.cat_data[:name], edit_category_path(sub_sub_category.cat_data[:id]) %>
	</td>
  <td>
		<%= link_to sub_sub_category.sub_cat_data[:name], edit_sub_category_path(sub_sub_category.sub_cat_data[:id]) %>
	</td>
	<td>
		<strong><%= sub_sub_category.name %></strong>
	</td>
  <td>
		<%= link_to 'Edit', edit_sub_sub_category_path(sub_sub_category), id: "edit_sub_sub_cat_#{sub_sub_category.id}" %>
	</td>
	<td>
		<%= link_to 'Delete', sub_sub_category_path(sub_sub_category), method: :delete, id: "delete_sub_sub_cat_#{sub_sub_category.id}_from_index" %>
	</td>
</tr>

app/views/sub_sub_categories/edit.html.erb
<h2>Edit <%= @sub_sub_category.name %></h2>

<%= render 'form' %>

app/views/sub_sub_categories/index.html.erb
<h2>Sub Sub Categories</h2>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				index
			</th>
			<th>
				Category
			</th>
      <th>
				Sub category
			</th>
			<th>
				Name
			</th>
      <th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%= render @sub_sub_categories %>
	</tbody>
</table>

<%= link_to 'Create new sub sub category', new_sub_sub_category_path, id: "new_sub_sub_cat_from_cat_index", class: 'btn btn-primary btn-block' %>

app/views/sub_sub_categories/new.html.erb
<h2>New Sub Sub Category</h2>

<%= render 'form' %>