config/routes.rb
Rails.application.routes.draw do

  root to: 'static#homepage'

  resources :products
  resources :sub_sub_categories
  resources :sub_categories
  resources :categories
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :sub_sub_categories, dependent: :destroy

  accepts_nested_attributes_for :sub_sub_categories,
                       reject_if: proc { |attributes| attributes['name'].blank? },
                   allow_destroy: true

  validates :name, presence: true
  validates :name, uniqueness: true

  def cat_data
    return { name: category.name,
               id: category.id }
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  def index
    @sub_categories = SubCategory.all.order("name DESC")
  end

  def new
    @sub_category = SubCategory.new
  end

  def create
    # debugger
    @sub_category = SubCategory.new(sub_category_params)

    if @sub_category.save
      redirect_to sub_categories_path, notice: 'Sub Category was successfully created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @sub_category.update(sub_category_params)
      redirect_to @sub_category, notice: 'Sub Category was successfully updated!'
    else
      render :edit
    end
  end

  def show
    @sub_sub_category = SubSubCategory.order("updated_at DESC").limit(5)
  end

  def destroy
    @sub_category.destroy
    redirect_to sub_categories_path, notice: 'Sub Category was successfully deleted'
  end

  private

  def sub_category_params
    params.require(:sub_category).permit(:name, :category_id, sub_sub_categories_attributes: [ :id, :name ])
  end

  def set_sub_category
    @sub_category = SubCategory.find(params[:id])
  end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_for @sub_category, class: "form-horizontal" do |f| %>

      <% if @sub_category.errors.any? %>
          <% @sub_category.errors.full_messages.each do |error| %>
          <%= js add_gritter(error, title: "Sephora App Notification", sticky: false) %>
        <% end %>
      <% end %>

      <div class="form-group">
        <%= f.label :category, class: "col-sm-2 control-label" %>
        <%= f.collection_select(:category_id, Category.all, :id, :name, { :multiple => false }, {class: "form-control"}) %>
      </div>

      <div class="form-group">
        <%= f.label :name, class: "col-sm-2 control-label" %>
        <%= f.text_area :name, class: "form-control" %>
      </div>

      <% unless create_page?(new_sub_category_path) %>
        <h3 class="text-center">Sub sub categories</h3>
        <%= link_to 'Create new sub sub category', new_sub_sub_category_path, class: 'btn btn-xs btn-primary btn-block' %></br>
        <%= f.fields_for :sub_sub_categories do |sub_sub_cat| %>
        <div class="form-group">
          <%= sub_sub_cat.label :sub_name, class: "col-sm-4 control-label" %>
          <%= sub_sub_cat.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= sub_sub_cat.label :_destroy, 'Remove', class: "pull-right" %>
          <%= sub_sub_cat.check_box :_destroy, class: "pull-right" %></br>
        </div>
        <% end %>
      <% end %>

      <%= f.submit 'Save', class: 'btn btn-lg btn-success btn-block' %>

    <% end %>
  </div>
</div>

app/views/sub_categories/_sub_category.html.erb
<tr>
	<td>
		<%= sub_category.id %>
	</td>
  <td>
		<%= link_to sub_category.cat_data[:name], edit_category_path(sub_category.cat_data[:id]) %>
	</td>
	<td>
		<strong><%= sub_category.name %></strong>
	</td>
  <td>
		<%= link_to 'Edit', edit_sub_category_path(sub_category), id: "edit_sub_cat_#{sub_category.id}" %>
	</td>
	<td>
		<%= link_to 'Delete', sub_category_path(sub_category), method: :delete, id: "delete_sub_cat_#{sub_category.id}_from_index" %>
	</td>
</tr>

app/views/sub_categories/edit.html.erb
<h2>Edit <%= @sub_category.name %></h2>

<%= render 'form' %>

app/views/sub_categories/index.html.erb
<h2>Sub Categories</h2>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				index
			</th>
      <th>
				Category
			</th>
			<th>
				Name
			</th>
      <th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%= render @sub_categories %>
	</tbody>
</table>

<%= link_to 'Create new sub category', new_sub_category_path, id: "new_sub_cat_from_cat_index", class: 'btn btn-primary btn-block' %>

app/views/sub_categories/new.html.erb
<h2>New Sub Category</h2>

<%= render 'form' %>

app/views/sub_categories/show.html.erb
<%= @sub_category.inspect %>

<%= @sub_sub_category.inspect %>