config/routes.rb
Rails.application.routes.draw do

  root to: 'static#homepage'

  resources :products
  resources :sub_sub_categories
  resources :sub_categories
  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, dependent: :destroy

  accepts_nested_attributes_for :sub_categories,
                       reject_if: proc { |attributes| attributes['name'].blank? },
                   allow_destroy: true

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all.order("name DESC")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated!'
    else
      render :edit
    end
  end

  def show
    # show last edited sub category
    @sub_category = SubCategory.order("updated_at DESC").limit(5)
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully deleted'
  end

  private

  def category_params
    params.require(:category).permit(:name, sub_categories_attributes: [ :id, :name, :_destroy ])
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
	<td>
		<%= category.id %>
	</td>
	<td>
		<strong><%= category.name %></strong>
	</td>
	<td>
		<%= link_to 'Edit', edit_category_path(category), id: "edit_#{category.id}" %>
	</td>
	<td>
		<%= link_to 'Delete', category_path(category), method: :delete, id: "delete_cat_#{category.id}_from_index" %>
	</td>
</tr>

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

    <%= form_for @category, class: "form-horizontal"  do |f| %>

    <% if @category.errors.any? %>
        <% @category.errors.full_messages.each do |error| %>
        <%= js add_gritter(error, title: "Sephora App Notification", sticky: false) %>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= f.label :Category_name, class: "col-sm-3 control-label" %>
      <%= f.text_area :name, class: "form-control" %>
    </div>

      <% unless create_page?(new_category_path) %>
      <h3>Sub categories</h3>
        <%= link_to 'Create new sub category', new_sub_category_path, class: 'btn btn-xs btn-primary btn-block' %></br>
        <%= f.fields_for :sub_categories do |sub_cat| %>
          <div class="form-group">
            <%= sub_cat.label :Sub_category_name, class: "col-sm-4 control-label" %>
            <%= sub_cat.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= sub_cat.label :_destroy, 'Remove', class: "pull-right" %>
            <%= sub_cat.check_box :_destroy, class: "pull-right" %></br>
          </div>
        <% end %>
      <% end %>

      <%= f.submit 'Save', class: 'btn btn-lg btn-success btn-block' %>

    <% end %>

  </div>
</div>

app/views/categories/edit.html.erb
<h2>Edit <%= @category.name %></h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				index
			</th>
			<th>
				name
			</th>
      <th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%= render @categories %>
	</tbody>
</table>

<%= link_to 'Create new category', new_category_path, id: "new_cat_from_cat_index", class: 'btn btn-primary btn-block' %>

app/views/categories/new.html.erb
<h2>New Category</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<%= @category.inspect %>

<%= @sub_category.inspect %>