config/routes.rb
Rails.application.routes.draw do

  root to: 'static#homepage'

  resources :products
  resources :sub_sub_categories
  resources :sub_categories
  resources :categories
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :sub_sub_category

  validates :name, :price, presence: true
  validates :name, uniqueness: true
  validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0 }

  def sub_sub_cat_data
    return { name: sub_sub_category.name,
               id: sub_sub_category.id }
  end

  def sub_cat_data
    return { name: sub_sub_category.sub_category.name,
               id: sub_sub_category.sub_category.id }
  end

  def cat_data
    return { name: sub_sub_category.sub_category.category.name,
               id: sub_sub_category.sub_category.category.id }
  end

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
    where("description ILIKE ?", "%#{search}%")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all.order("name DESC")
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: 'Product successfully created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: 'Product successfully updated!'
    else
      render :edit
    end
  end

  def show
    @products_updated = Product.order("updated_at DESC").limit(5)
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: 'Product successfully deleted'
  end

  private

  def product_params
    params.require(:product).permit(:name,
                                    :description,
                                    :thumb_img,
                                    :price,
                                    :sub_sub_category_id)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_for @product, class: "form-horizontal" do |f| %>

      <% if @product.errors.any? %>
          <% @product.errors.full_messages.each do |error| %>
          <%= js add_gritter(error, title: "Sephora App Notification", sticky: false) %>
        <% end %>
      <% end %>

      <div class="form-group">
        <%= f.label :name, class: "col-sm-2 control-label" %>
        <%= f.text_area :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description, class: "col-sm-2 control-label" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :price, class: "col-sm-2 control-label" %>
        <%= f.number_field :price, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :thumb_img, class: "col-sm-2 control-label" %>
        <%= f.text_area :thumb_img, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :sub_sub_category, class: "col-sm-4 control-label" %>
        <%= f.grouped_collection_select(:sub_sub_category_id, SubCategory.all, :sub_sub_categories, :name, :id, :name, { :multiple => false }, {class: "form-control"}) %>
      </div>

      <%= link_to 'Create new sub sub category', new_sub_sub_category_path, class: 'btn btn-xs btn-primary btn-block' %>
      <%= f.submit 'Save', class: 'btn btn-lg btn-success btn-block' %>

    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<tr>
	<td>
		<%= product.id %>
	</td>
	<td>
		<%= link_to product.cat_data[:name], edit_category_path(product.cat_data[:id]) %>
	</td>
	<td>
		<%= link_to product.sub_cat_data[:name], edit_sub_category_path(product.sub_cat_data[:id]) %>
	</td>
  <td>
		<%= link_to product.sub_sub_cat_data[:name], edit_sub_sub_category_path(product.sub_sub_cat_data[:id]) %>
	</td>
	<td>
		<strong><%= product.name %></strong>
	</td>
  <td>
		<%= link_to 'Edit', edit_product_path(product), id: "edit_prod_#{product.id}" %>
	</td>
	<td>
		<%= link_to 'Delete', product_path(product), method: :delete, id: "delete_prod_#{product.id}_from_index" %>
	</td>
</tr>

app/views/products/edit.html.erb
<h2>Edit <%= @product.name %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<h2>Products</h2>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				index
			</th>
			<th>
				Category
			</th>
			<th>
				Sub category
			</th>
      <th>
				Sub Sub category
			</th>
			<th>
				name
			</th>
      <th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%= render @products %>
	</tbody>
</table>

<%= link_to 'Create product', new_product_path, id: "new_prod_from_cat_index", class: 'btn btn-primary btn-block' %>

app/views/products/new.html.erb
<h2>New Product</h2>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="panel panel-default  panel--styled">
	<div class="panel-body">
		<div class="col-md-12 panelTop">
			<div class="col-md-4">
				<img class="img-responsive" src="http://placehold.it/350x350" alt=""/>
			</div>
			<div class="col-md-8">
				<h2><%= @product.name %></h2>
				<p><%= @product.description %></p>
			</div>
		</div>

		<div class="col-md-12 panelBottom">
			<div class="col-md-4 text-center">
				<button class="btn btn-lg btn-add-to-cart"><span class="glyphicon glyphicon-shopping-cart"></span>   Add to Cart</button>
			</div>
			<div class="col-md-4 text-left">
				<h5>Price <span class="itemPrice">$<%= @product.price %></span></h5>
			</div>
			<div class="col-md-4">
				<div class="stars">
				 <div id="stars" class="starrr"></div>
				</div>
			</div>
		</div>
	</div>
</div>